name: WebApps-React Package Tests

on:
  push:
    branches:
      - develop
      - "release/**"
  pull_request:
    branches:
      - develop
      - "future/**"

jobs:
  js-tests:
    runs-on: ubuntu-latest
    name: UI/UX Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Compile assets
        run: |
          npm install
          npm run build
      - name: Run UI Tests
        run: npm run test-coverage
      - name: Upload UI coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          flags: uitests
          name: codecov-umrella
          fail_ci_if_error: true